### ISSUE TITLE
Move HiddenThread component to Components codebase

### ISSUE THREAD

**Issue by virtuous-cat** [BobaBoard/boba-frontend#68]
- [x] Move [`HiddenThread`](https://github.com/essential-randomness/boba-frontend/blob/7909c4e76cd67cb789dda6d7b476b51b6553623d/components/ThreadPreview.tsx#L42) from `ThreadPreview.tsx` in Frontend codebase to Components codebase

**Comment by essential-randomness** [comment]
Fixed by https://github.com/BobaBoard/boba-components/pull/127
